### ISSUE TITLE
Add option to cleanup old lambda versions

### ISSUE THREAD

**Issue by ryandub** [rackerlabs/yoke#54]
We need to add the ability to clean up old lambda versions and keep a specified number in order to properly control the size of Lambda code storage.

What about a `keepVersions` key in the `Lambda` config object in `yoke.yml`?

```
Lambda:
  config:
    name: &name app
    runtime: python3.6
    description: &desc Description
    handler: "handler.lambda_handler"
    timeout: 300
    memory: 256
    ignore: ["/*.pyc"]
    role: {{ LAMBDA_EXECUTION_ROLE }}
    tracing:
      Mode: Active
  path: './src'
  dependencies:
    wheelhouse_path: './wheelhouse'
    build: true
  extraFiles:
    - './lib/'
  keepVersions: 10
```
